config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' } 

  resources :users
  root to: "home#index"

  resources :enrollments
  resources :presences
  resources :major_disciplines
  resources :professors
  resources :classrooms
  resources :periods
  resources :lectures
  resources :students
  resources :disciplines
  resources :majors
  resources :departments
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if !user.admin?
      can :edit, User, :id => user.id
    else
      can :manage, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    belongs_to :professor
    belongs_to :period
    belongs_to :discipline
    has_many :lectures

    has_many :enrollments
    has_many :students, through: :enrollments

end

app/models/department.rb
class Department < ApplicationRecord
    has_many :professors
    has_many :discipline
    has_many :major
end

app/models/discipline.rb
class Discipline < ApplicationRecord
    belongs_to :department
    belongs_to :classroom, optional: true
    has_and_belongs_to_many :equivalences,
        class_name: "Discipline",
        join_table: :equivalences,
        foreign_key: :disc_id,
        association_foreign_key: :eq_disc_id

    has_many :major_disciplines
    has_many :majors, through: :major_disciplines

    has_many :equivalences
    has_many :eq_disciplines, through: :equivalences

    has_many :equivalents, foreign_key: :eq_discipline_id, class_name: 'Equivalence'
    has_many :equivalent_disciplines, through: :equivalents, source: :discipline

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
    belongs_to :discipline
    belongs_to :eq_discipline, class_name: 'Discipline'
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    belongs_to :classroom

    has_many :presences
    has_many :students, through: :presences
end

app/models/major.rb
class Major < ApplicationRecord
    belongs_to :department
    has_many :students

    has_many :major_disciplines
    has_many :disciplines, through: :major_disciplines
end

app/models/major_discipline.rb
class MajorDiscipline < ApplicationRecord
  belongs_to :major
  belongs_to :discipline
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :student
  belongs_to :lecture
end

app/models/professor.rb
class Professor < ApplicationRecord
    has_many :classrooms
    belongs_to :department
    belongs_to :user
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :major

    has_many :enrollments
    has_many :classrooms, through: :enrollments

    has_many :presences
    has_many :lectures, through: :presences

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one :professor

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  enum kind: {
    standard: 0,
    admin: 1,
    teacher: 2,
    coord: 3
  } 


end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.where(["name LIKE ?","%#{params[:search]}%"])
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:department_id, :name, {:major_ids => [] } , {:eq_discipline_ids => [] } )
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def user_kind_options
        [['Administrador', :admin],['Padrão', :standard],["Professor", :teacher],["Coordenador", :coord]]
    end

    def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end

end

app/views/disciplines/_form.html.erb
<%= form_with(model: discipline, local: true) do |form| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :department %>
    <%= form.select :department_id, options_for_select(Department.all.map{|s|[s.name, s.id]}) %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
      <%= hidden_field_tag "discipline[major_ids][]", nil%>
      <%= form.label "Curso" %>
      <% Major.all.each do |major| %>
        <%= check_box_tag "discipline[major_ids][]", major.id, @discipline.major_ids.include?(major.id), id: dom_id(major)%>
        <%= label_tag dom_id(major), major.name %>
      <% end %>
  </div>

  <div class="field">
      <%= hidden_field_tag "discipline[eq_discipline_ids][]", nil%>
      <%= form.label "Disciplinas Equivalentes" %>
      <% Discipline.all.each do |eq_discipline| %>
        <%= check_box_tag "discipline[eq_discipline_ids][]", eq_discipline.id, @discipline.eq_discipline_ids.include?(eq_discipline.id), id: dom_id(eq_discipline)%>
        <%= label_tag dom_id(eq_discipline), eq_discipline.name %>
      <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editando Disciplina</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Mostrar', @discipline %> |
<%= link_to 'Voltar', disciplines_path %>

app/views/disciplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplinas</h1>

<%= form_tag disciplines_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Pesquisar" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Departmento</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.department.name %></td>
        <td><%= discipline.name %></td>
        <td><%= link_to 'Mostrar', discipline %></td>
        <% if current_user.admin? or current_user.coord? %>
          <td><%= link_to 'Editar', edit_discipline_path(discipline) %></td>
          <td><%= link_to 'Excluir', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? or current_user.coord? %>
  <%= link_to 'Nova Disciplina', new_discipline_path %>
<% end %>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departmento:</strong>
  <%= @discipline.department.name %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @discipline.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Cursos:</th>
    </tr>
  </thead>
  <tbody>
    <% @discipline.majors.each do |major| %>
      <tr>
        <td><%= major.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Equivalentes:</th>
    </tr>
  </thead>
  <tbody>
    <% @discipline.eq_disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.admin? or current_user.coord? %>
  <%= link_to 'Editar', edit_discipline_path(@discipline) %> |
  <%= link_to 'Voltar', disciplines_path %>
<% end %>